### ISSUE TITLE
Multiple USER_FOUND actions being dispatched on page refresh

### ISSUE THREAD

**Issue by nloding** [maxmantz/redux-oidc#63]
My implementation of `redux-oidc` is nearly identical to the `redux-oidc-example`, and I can share what bits need to be shared, I just don't know what is helpful right now. The `USER_FOUND` event is being fired several times when the page is refreshed. The screenshot shared below shows the ReduxDevTools listing of the events. `LOADING_USER` is fired twice, `USER_EXPIRED` is fired twice before that, and it ends with `USER_FOUND` twice. I've seen `USER_FOUND` three or four times also.

I was listening for the `USER_FOUND` event in my own middleware to fetch the user profile back into state like so:

```
export default function oidcUserLoaderMiddleware(store) {
  return next => action => {
    if (action.type == USER_FOUND) {
      store.dispatch(loadUserToStore())
    }

    return next(action)
  }
}
```

Because `USER_FOUND` is fired multiple times, I'm making a couple unnecessary calls to my API. They aren't really harmful, just unnecessary and that's how I noticed the duplicated dispatches.

I'm not sure if this is expected? If not, is this a bug in `redux-oidc` or a bug in my code that is causing `redux-oidc` to get confused?

https://www.dropbox.com/s/l7ie38ku9kl5u3y/Screenshot%202017-09-29%2014.55.12.png?dl=0

**Comment by maxmantz** [comment]
How have you set up the userManager loading process? Are you using `loadUser` or the middleware?

**Comment by maxmantz** [comment]
Any update on this?

**Comment by nloding** [comment]
Sorry, missed the original notification. I'm using the middleware, and here is how I've configured it:

```
import createOidcMiddleware, { createUserManager } from 'redux-oidc'

import config from 'config' // eslint-disable-line import/no-unresolved

let uri = `${window.location.protocol}//${window.location.hostname}`
if (window.location.port && window.location.port != "80" && window.location.port != "443") {
  uri = `${uri}:${window.location.port}`
}

// oidc configuration
export const oidcConfig = {
  client_id: 'my-ui',
  redirect_uri: `${uri}/login-callback`,
  response_type: 'id_token token',
  scope: 'openid profile my-api',
  authority: config.authUrl,
  post_logout_redirect_uri: `${uri}/logout-callback`,
  silent_redirect_uri: `${uri}/silent_renew.html`,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true
}

export const oidcUserManager = createUserManager(oidcConfig)

const oidcMiddleware = createOidcMiddleware(
  oidcUserManager,
  () => true, // shouldValidate
  false, // triggerAuthFlow - do not redir to oidc when user is expired
  '/login-callback' // callbackRoute
)

export default oidcMiddleware
```

The `oidcMiddleware` is then applied in my store the usual way.

**Comment by maxmantz** [comment]
No problem, thanks for sharing your configs. I think I've found the issue. 

When you are using silent renew you don't need the middleware. Please use the `loadUser` helper function instead. [This is how it is used in the example app](https://github.com/maxmantz/redux-oidc-example/blob/master/src/store.js#L30). If you are accidentally using both, this will explain why `USER_FOUND` is dispatched multiple times.

**Comment by nloding** [comment]
Gotcha. I'm not sure which approach is more appropriate for my app right now, I'll have to do some reading. Thanks!

**Comment by maxmantz** [comment]
In general, setting up silent renew is the best approach. It allows for silently refreshing the token. There is no reason not to do it, unless your setup prevents it.

**Comment by borntorun** [comment]
I think there is a problem in the middleware that is causing multiple dispatchs of 'redux-oidc/LOADING_USER' actions that cause identical number of 'redux-oidc/USER_FOUND' dispatchs: 

This function:

```
export function middlewareHandler(next, action, userManager) {
  // prevent an infinite loop of dispatches of these action types (issue #30)
  if (action.type === USER_EXPIRED || action.type === LOADING_USER) {
    return next(action);
  }

  nextMiddleware = next;

  if (!storedUser || storedUser.expired) { // <----- condition
    next(loadingUser());
    userManager.getUser()
      .then(getUserCallback)
      .catch(errorCallback);
  }
  return next(action);
}
```

will trigger all actions dispatched while the condition returns true triggering the 'loadingUser' action on the next line and the related code.  Depending on each implementation that can cause problems; In my case my app code is just 'responding' to the first 'redux-oidc/USER_FOUND' action. 

Thanks.

**Comment by maxmantz** [comment]
Were you able to solve this issue?

**Comment by nloding** [comment]
@maxmantz unfortunately no, but I haven't done more digging. I think @borntorun is on to something there. Even if I set `automaticSilentRenew` to `false`, I still get 3-4 `USER_FOUND` dispatches.

**Comment by maxmantz** [comment]
Fixed in beta.14. Thanks for the bug report and fix @nloding  & @borntorun.

**Comment by nloding** [comment]
@maxmantz awesome, I'm running beta.10, I'll update soon and confirm!

**Comment by nloding** [comment]
@maxmantz I'm now running beta.14 with the same config as above, except with `automaticSilentRenew: false`, and still getting multiple dispatches. Any thoughts?

<img width="670" alt="screenshot 2017-11-27 12 56 24" src="https://user-images.githubusercontent.com/328425/33281305-b93c83de-d372-11e7-99e4-e59a63adf88f.png">

**Comment by maxmantz** [comment]
No - from the information I have I cannot reproduce this behavior. However I strongly suggest switching from the middleware to the `loadUser` helper if you have silent renew set up (maybe you are already using both?).

**Comment by nloding** [comment]
@maxmantz I'll do some more looking, and see if I can switch from the middleware to `loadUser` and see how that changes things. I'll report back later either way!

**Comment by bohdanbirdie** [comment]
I'm actually facing the same issue on `3.0.0-beta.16` and `3.0.0-beta.14`
Removing middleware helped.

**Comment by kaitmore** [comment]
Also facing this issue on 3.0.0-beta.16
I don't want silent renew, so I just have the middleware set up (no loadUser) and am still seeing this.

**Comment by maxmantz** [comment]
I investigated this issue furhter and from my understanding it is caused by two things: 
1. the middleware dispatches the action when the user is loaded,
2. the oidc provider also dispatches the action when the user is loaded.

I've tried removing the dispatch from both the middleware and oidc provider. The problems resulting from this are:
1. When the middleware dosen't dispatch the action, on page reload the user object is lost and a new login is necessary.
2. When the oidc provider doesn't dispatch the action, on silent renew, the new user object doesn't get dispatched, thus breaking functionality.

In light of this discovery, I think it is best to live with the (rather small) inconvenience of having multiple dispatches on startup instead of sacrificing important functionality at the core of this library.
